import 'package:scryfall_api/scryfall_api.dart';

final mtgCardCreatureMockup = MtgCard(
  id: '1',
  power: '10',
  toughness: '10',
  imageUris: ImageUris(
    small: Uri(path: 'http://small/img/sample'),
    normal: Uri(path: 'http://normal/img/sample'),
    large: Uri(path: 'http://large/img/sample'),
    png: Uri(path: 'http://png/img/sample'),
    artCrop: Uri(path: 'http://artCrop/img/sample'),
    borderCrop: Uri(path: 'http://borderCrop/img/sample'),
  ),
  name: 'Test Token',
  oracleText: 'Sample text',
  typeLine: 'Creature',
  lang: Language.english,
  oracleId: 'oracleId',
  printsSearchUri: Uri(path: 'http://printsSearchUri/sample'),
  rulingsUri: Uri(path: 'http://rulingsUri/sample'),
  scryfallUri: Uri(path: 'http://scryfallUri/sample'),
  uri: Uri(path: 'http://uri/sample'),
  cmc: 0,
  colorIdentity: [Color.red, Color.green],
  keywords: [],
  layout: Layout.normal,
  legalities: const Legalities(
      standard: Legality.legal,
      future: Legality.legal,
      historic: Legality.legal,
      timeless: Legality.legal,
      gladiator: Legality.legal,
      pioneer: Legality.legal,
      explorer: Legality.legal,
      modern: Legality.legal,
      legacy: Legality.legal,
      pauper: Legality.legal,
      vintage: Legality.legal,
      penny: Legality.legal,
      commander: Legality.legal,
      oathbreaker: Legality.legal,
      brawl: Legality.legal,
      standardbrawl: Legality.legal,
      alchemy: Legality.legal,
      paupercommander: Legality.legal,
      duel: Legality.legal,
      oldschool: Legality.legal,
      premodern: Legality.legal,
      predh: Legality.legal),
  oversized: false,
  reserved: false,
  booster: false,
  borderColor: BorderColor.black,
  cardBackId: 'cardBackId',
  collectorNumber: 'collectorNumber',
  contentWarning: false,
  digital: false,
  foil: false,
  nonfoil: false,
  finishes: [],
  frame: Frame.classic_1993,
  fullArt: false,
  games: [],
  highresImage: false,
  imageStatus: ImageStatus.lowres,
  prices: const Prices(
    usd: 'usd',
    usdFoil: 'usdFoil',
    eur: 'eur',
    tix: 'tix',
  ),
  promo: false,
  purchaseUris: {},
  rarity: Rarity.common,
  relatedUris: {},
  releasedAt: DateTime.now(),
  reprint: false,
  scryfallSetUri: Uri(path: 'http://scryfallSetUri/sample'),
  setName: 'setName',
  setSearchUri: Uri(path: 'http://setSearchUri/sample'),
  setType: SetType.core,
  setUri: Uri(path: 'http://setUri/sample'),
  set: 'set',
  setId: 'setId',
  storySpotlight: false,
  textless: false,
  variation: false,
);

final mtgCardStarCreatureMockup = MtgCard(
  id: '1',
  power: '*',
  toughness: '*',
  imageUris: ImageUris(
    small: Uri(path: 'http://small/img/sample'),
    normal: Uri(path: 'http://normal/img/sample'),
    large: Uri(path: 'http://large/img/sample'),
    png: Uri(path: 'http://png/img/sample'),
    artCrop: Uri(path: 'http://artCrop/img/sample'),
    borderCrop: Uri(path: 'http://borderCrop/img/sample'),
  ),
  name: 'Test Token',
  oracleText: 'Sample text',
  typeLine: 'Creature',
  lang: Language.english,
  oracleId: 'oracleId',
  printsSearchUri: Uri(path: 'http://printsSearchUri/sample'),
  rulingsUri: Uri(path: 'http://rulingsUri/sample'),
  scryfallUri: Uri(path: 'http://scryfallUri/sample'),
  uri: Uri(path: 'http://uri/sample'),
  cmc: 0,
  colorIdentity: [],
  keywords: [],
  layout: Layout.normal,
  legalities: const Legalities(
      standard: Legality.legal,
      future: Legality.legal,
      historic: Legality.legal,
      timeless: Legality.legal,
      gladiator: Legality.legal,
      pioneer: Legality.legal,
      explorer: Legality.legal,
      modern: Legality.legal,
      legacy: Legality.legal,
      pauper: Legality.legal,
      vintage: Legality.legal,
      penny: Legality.legal,
      commander: Legality.legal,
      oathbreaker: Legality.legal,
      brawl: Legality.legal,
      standardbrawl: Legality.legal,
      alchemy: Legality.legal,
      paupercommander: Legality.legal,
      duel: Legality.legal,
      oldschool: Legality.legal,
      premodern: Legality.legal,
      predh: Legality.legal),
  oversized: false,
  reserved: false,
  booster: false,
  borderColor: BorderColor.black,
  cardBackId: 'cardBackId',
  collectorNumber: 'collectorNumber',
  contentWarning: false,
  digital: false,
  foil: false,
  nonfoil: false,
  finishes: [],
  frame: Frame.classic_1993,
  fullArt: false,
  games: [],
  highresImage: false,
  imageStatus: ImageStatus.lowres,
  prices: const Prices(
    usd: 'usd',
    usdFoil: 'usdFoil',
    eur: 'eur',
    tix: 'tix',
  ),
  promo: false,
  purchaseUris: {},
  rarity: Rarity.common,
  relatedUris: {},
  releasedAt: DateTime.now(),
  reprint: false,
  scryfallSetUri: Uri(path: 'http://scryfallSetUri/sample'),
  setName: 'setName',
  setSearchUri: Uri(path: 'http://setSearchUri/sample'),
  setType: SetType.core,
  setUri: Uri(path: 'http://setUri/sample'),
  set: 'set',
  setId: 'setId',
  storySpotlight: false,
  textless: false,
  variation: false,
);

final mtgCardNonCreatureMockup = MtgCard(
  id: '1',
  power: null,
  toughness: null,
  imageUris: ImageUris(
    small: Uri(path: 'http://small/img/sample'),
    normal: Uri(path: 'http://normal/img/sample'),
    large: Uri(path: 'http://large/img/sample'),
    png: Uri(path: 'http://png/img/sample'),
    artCrop: Uri(path: 'http://artCrop/img/sample'),
    borderCrop: Uri(path: 'http://borderCrop/img/sample'),
  ),
  name: 'Test Token',
  oracleText: 'Sample text',
  typeLine: 'Artifact',
  lang: Language.english,
  oracleId: 'oracleId',
  printsSearchUri: Uri(path: 'http://printsSearchUri/sample'),
  rulingsUri: Uri(path: 'http://rulingsUri/sample'),
  scryfallUri: Uri(path: 'http://scryfallUri/sample'),
  uri: Uri(path: 'http://uri/sample'),
  cmc: 0,
  colorIdentity: [],
  keywords: [],
  layout: Layout.normal,
  legalities: const Legalities(
      standard: Legality.legal,
      future: Legality.legal,
      historic: Legality.legal,
      timeless: Legality.legal,
      gladiator: Legality.legal,
      pioneer: Legality.legal,
      explorer: Legality.legal,
      modern: Legality.legal,
      legacy: Legality.legal,
      pauper: Legality.legal,
      vintage: Legality.legal,
      penny: Legality.legal,
      commander: Legality.legal,
      oathbreaker: Legality.legal,
      brawl: Legality.legal,
      standardbrawl: Legality.legal,
      alchemy: Legality.legal,
      paupercommander: Legality.legal,
      duel: Legality.legal,
      oldschool: Legality.legal,
      premodern: Legality.legal,
      predh: Legality.legal),
  oversized: false,
  reserved: false,
  booster: false,
  borderColor: BorderColor.black,
  cardBackId: 'cardBackId',
  collectorNumber: 'collectorNumber',
  contentWarning: false,
  digital: false,
  foil: false,
  nonfoil: false,
  finishes: [],
  frame: Frame.classic_1993,
  fullArt: false,
  games: [],
  highresImage: false,
  imageStatus: ImageStatus.lowres,
  prices: const Prices(
    usd: 'usd',
    usdFoil: 'usdFoil',
    eur: 'eur',
    tix: 'tix',
  ),
  promo: false,
  purchaseUris: {},
  rarity: Rarity.common,
  relatedUris: {},
  releasedAt: DateTime.now(),
  reprint: false,
  scryfallSetUri: Uri(path: 'http://scryfallSetUri/sample'),
  setName: 'setName',
  setSearchUri: Uri(path: 'http://setSearchUri/sample'),
  setType: SetType.core,
  setUri: Uri(path: 'http://setUri/sample'),
  set: 'set',
  setId: 'setId',
  storySpotlight: false,
  textless: false,
  variation: false,
);
